version: "3.7"

services:
  indexer:
    build: ../indexer
    ports:
      - 8007:8007
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      POSTGRES_URL: docker_postgres_db_1
      POSTGRES_DB: bookstore
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    networks:
      - intellisite

networks:
   intellisite:
     external: true
