version: "3.7"

services:
  postgres_db:
    image: postgres:11.1
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
      POSTGRES_USER: root
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - intellisite
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

networks:
   intellisite:
     external: true
