version: "3.7"

services:
  indexer:
    build: ../indexer
    ports:
      - 8007:8007
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
    networks:
      - intellisite

networks:
  default:
   external:
     name: intellisite
